apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
  namespace: stf # Используйте ваш целевой namespace
  labels:
    app: dummy-service
spec:
  replicas: 1 # Количество реплик, можно увеличить для масштабирования
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
        - name: dummy-service
          image: registry.dmz.home/kinga/stream-forge/dummy-service:1.0.0 # Используйте ваш актуальный образ и версию
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "k3-kafka-bootstrap.kafka:9093"
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: dummy-service-secret
                  key: KAFKA_USER
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dummy-service-secret
                  key: KAFKA_PASSWORD
            - name: QUEUE_EVENTS_TOPIC
              value: "queue-events"
            - name: QUEUE_CONTROL_TOPIC
              value: "queue-control"
            - name: QUEUE_ID
              value: "dummy-test-local"
            - name: TELEMETRY_PRODUCER_ID
              value: "dummy-local-instance"
            - name: CA_PATH
              value: "/usr/local/share/ca-certificates/ca.crt" # Путь монтирования CA-сертификата
            # Дополнительные переменные окружения, если нужны для вашего сценария
            - name: ARANGO_DB
              value: "streamforge"
            - name: ARANGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dummy-service-secret
                  key: ARANGO_PASSWORD
            - name: ARANGO_URL
              value: "http://abase-3.dmz.home:8529"
            - name: ARANGO_USER
              value: "root"
            - name: KAFKA_TOPIC
              value: "BTCUSDT-rest"
            - name: SYMBOL
              value: "BTCUSDT"
            - name: TIME_RANGE
              value: "2024-01-01:2024-01-02"
            - name: TYPE
              value: "dummy"
          volumeMounts:
            - name: kafka-ca-volume
              mountPath: /usr/local/share/ca-certificates/ca.crt
              subPath: dev-ca.crt # Имя файла сертификата внутри ConfigMap
              readOnly: true
          command: ["python3.11"]
          args: ["-m", "app.main", "--debug", "--simulate-loading"] # Команда для запуска dummy-service
          ports:
            - containerPort: 8000 # Порт для метрик Prometheus
              name: metrics
          livenessProbe: # Проверка живости
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe: # Проверка готовности
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: kafka-ca-volume
          configMap:
            name: dev-ca-certificates # Имя вашего ConfigMap с CA-сертификатом
            items:
              - key: dev-ca.crt # Ключ, под которым хранится сертификат в ConfigMap
                path: ca.crt
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: stf # Используйте ваш целевой namespace
  labels:
    app: dummy-service
spec:
  selector:
    app: dummy-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: metrics
      name: metrics
