include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

test-dummy-service:
  extends: .test_python_service
  variables:
    SERVICE_NAME: dummy-service
    SERVICE_PATH: services/dummy-service
    LOGURU_LEVEL: DEBUG # Add this line
  when: manual

build-dummy-service:
  extends: .build_python_service
  needs:
    - test-dummy-service
  variables:
    SERVICE_NAME: dummy-service
    SERVICE_PATH: services/dummy-service
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/dummy-service

integration-test-dummy-service:
  extends: .integration_test_python_service
  needs:
    - build-dummy-service
  variables:
    SERVICE_NAME: dummy-service
    SERVICE_PATH: services/dummy-service
  when: manual # Make it manual for now, user can change later
  before_script:
    - apt-get update && apt-get install -y curl
    - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR/$SERVICE_PATH/app # Add app directory to PYTHONPATH
    - python -m main --noop & # Start the service
    - |-
      echo "Waiting for service to start..."
      for i in $(seq 1 30); do
        if curl -s http://localhost:8000/metrics > /dev/null; then
          echo "Service is up!"
          break
        fi
        echo "Service not ready yet. Waiting ${i}s..."
        sleep ${i}
      done
      curl http://localhost:8000/metrics # Show metrics for debugging

deploy-dummy-service:
  extends: .deploy_kubernetes_service
  needs:
    - integration-test-dummy-service
  variables:
    K8S_MANIFEST_PATH: services/dummy-service/k8s/dummy-service-deployment.yaml

update-badge-dummy-service:
  extends: .update_badge_python_service
  needs:
    - deploy-dummy-service
  variables:
    SERVICE_NAME: dummy-service
    SERVICE_PATH: services/dummy-service