apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-test
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "b2bb72ab-f6ce-445d-b19d-b4feda58af96"
    keyvaultName: "marketflow-vault"
    cloudName: ""
    tenantId: "7f776ea7-75ee-492e-83f3-40a9552b9320"
    objects: |
      array:
        - |
          objectName: KafkaConnectionString
          objectType: secret
        - |
          objectName: SnowflakeConnectionString
          objectType: secret
---
apiVersion: v1
kind: Pod
metadata:
  name: kv-test
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: azure-kv-test

