apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user-streamforge
  namespace: kafka
  labels:
    strimzi.io/cluster: k3
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple