marketflow:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ANALYST') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'MARKETFLOW_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'MARKETFLOW_DB') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STAGING') }}"
      threads: 4
      client_session_keep_alive: False
